# Generated by Django 5.2.7 on 2025-12-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0022_alter_product_options_remove_product_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, max_length=255)),
                ('serial_number', models.CharField(default='SN-XXXX-XXXX', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('owned', 'Owned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristicsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics_blocks', to='portal.portalproduct')),
            ],
            options={
                'verbose_name': 'Product characteristics block',
                'verbose_name_plural': 'Product characteristics blocks',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic', to='portal.portalproduct')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='portal.productcharacteristicsblock')),
            ],
            options={
                'verbose_name': 'Product characteristic',
                'verbose_name_plural': 'Product characteristics',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('is_preview', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.portalproduct')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('button_text', models.CharField(default='Request', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='portal.portalproduct')),
            ],
            options={
                'verbose_name': 'Product module',
                'verbose_name_plural': 'Product modules',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductModuleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_images', to='portal.productmodule')),
            ],
            options={
                'verbose_name': 'Product module image',
            },
        ),
        migrations.CreateModel(
            name='ProductModulesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_blocks', to='portal.portalproduct')),
            ],
            options={
                'verbose_name': 'Product modules block',
                'verbose_name_plural': 'Product modules blocks',
            },
        ),
        migrations.AddField(
            model_name='productmodule',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='portal.productmodulesblock'),
        ),
    ]
