# Generated by Django 5.2.7 on 2025-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristicsblock',
            options={},
        ),
        migrations.RemoveField(
            model_name='productcharacteristicsblock',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='productcharacteristicsblock',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_icons/'),
        ),
        migrations.AddField(
            model_name='productcharacteristicsblock',
            name='icon_lucide',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productcharacteristicsblock',
            name='icon_type',
            field=models.CharField(choices=[('lucide', 'Lucide'), ('upload', 'Upload')], default='lucide', max_length=10),
        ),
    ]
