# Generated by Django 5.2.7 on 2025-12-22 15:28

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_productcharacteristicsblock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalproduct',
            options={'ordering': ('order', '-created_at'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='portalproduct',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portalproduct',
            name='tags',
            field=models.JSONField(blank=True, default=portal.models.default_tags, help_text="List of tags (strings). Example: ['uav', 'vtol']"),
        ),
    ]
