# Generated by Django 5.2.7 on 2025-12-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_portalproduct_options_portalproduct_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalproduct',
            name='status',
        ),
    ]
