# Generated by Django 5.2.7 on 2025-12-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_remove_portalproduct_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModuleCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_characteristics",
                        to="portal.productmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product module characteristic",
                "verbose_name_plural": "Product module characteristics",
                "ordering": ("order",),
            },
        ),
    ]
