# Generated by Django 5.2.7 on 2025-12-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_productmodulecharacteristic"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("text", models.TextField(max_length=1024)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_blocks",
                        to="portal.portalproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product text block",
                "verbose_name_plural": "Product text blocks",
                "ordering": ("order",),
            },
        ),
    ]
