# Generated by Django 5.2.7 on 2025-12-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_productpresentationinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpresentationinfo",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
