# Generated by Django 5.2.7 on 2025-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_productpresentationinfo_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpresentationinfo',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Product presentation info', 'verbose_name_plural': 'Product presentation info'},
        ),
        migrations.AlterField(
            model_name='productpresentationinfo',
            name='description',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='producttextblock',
            name='text',
            field=models.TextField(max_length=2048),
        ),
    ]
