# Generated by Django 5.2.7 on 2025-12-27 18:45

from django.db import migrations, models
import django.db.models.deletion


def forwards_create_module_placements(apps, schema_editor):
    ProductModule = apps.get_model("portal", "ProductModule")
    ProductModulePlacement = apps.get_model("portal", "ProductModulePlacement")
    placements = []
    for module in ProductModule.objects.all().iterator():
        if module.product_id is None:
            continue
        placements.append(
            ProductModulePlacement(
                product_id=module.product_id,
                module_id=module.id,
                block_id=module.block_id,
                order=module.order,
            )
        )
    if placements:
        ProductModulePlacement.objects.bulk_create(placements)


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_alter_productpresentationinfo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModulePlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="module_placements",
                        to="portal.productmodulesblock",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="portal.productmodule",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_placements",
                        to="portal.portalproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "verbose_name": "Product module placement",
                "verbose_name_plural": "Product module placements",
            },
        ),
        migrations.AddField(
            model_name="productmodule",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="modules",
                through="portal.ProductModulePlacement",
                to="portal.portalproduct",
            ),
        ),
        migrations.RunPython(
            forwards_create_module_placements, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="productmodule",
            name="block",
        ),
        migrations.RemoveField(
            model_name="productmodule",
            name="order",
        ),
        migrations.RemoveField(
            model_name="productmodule",
            name="product",
        ),
    ]
