# Generated by Django 5.2.7 on 2025-12-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_productmoduleplacement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodule',
            options={'verbose_name': 'Product module', 'verbose_name_plural': 'Product modules'},
        ),
    ]
