# Generated by Django 5.2.7 on 2025-12-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_productmodule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodule',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='productmodulecharacteristic',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='productmodulecharacteristic',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
