# Generated by Codex on 2025-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_alter_productmodule_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalproduct",
            name="name_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portalproduct",
            name="name_sk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portalproduct",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portalproduct",
            name="description_sk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productcharacteristic",
            name="name_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productcharacteristic",
            name="name_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productcharacteristic",
            name="description_de",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productcharacteristic",
            name="description_sk",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productcharacteristicsblock",
            name="title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productcharacteristicsblock",
            name="title_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="alt_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="alt_sk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_sk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="button_text_de",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="button_text_sk",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="description_de",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="description_sk",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="name_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="name_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="tag_de",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="productmodule",
            name="tag_sk",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="productmodulecharacteristic",
            name="description_de",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="productmodulecharacteristic",
            name="description_sk",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="productmodulecharacteristic",
            name="name_de",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productmodulecharacteristic",
            name="name_sk",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productmoduleimage",
            name="alt_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productmoduleimage",
            name="alt_sk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productmodulesblock",
            name="subtitle_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productmodulesblock",
            name="subtitle_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productmodulesblock",
            name="title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productmodulesblock",
            name="title_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productpresentationinfo",
            name="title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productpresentationinfo",
            name="title_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productpresentationinfo",
            name="description_de",
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="productpresentationinfo",
            name="description_sk",
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="producttextblock",
            name="title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="producttextblock",
            name="title_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="producttextblock",
            name="text_de",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="producttextblock",
            name="text_sk",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
