# Generated by Django 4.2.27 on 2026-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_modeltranslation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalproduct',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalproduct',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='description_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristicsblock',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='button_text_en',
            field=models.CharField(default='Request', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='tag_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='description_en',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productmoduleimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='subtitle_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='description_en',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='text_en',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='portalproduct',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portalproduct',
            name='name_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productcharacteristic',
            name='name_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productcharacteristic',
            name='name_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productcharacteristicsblock',
            name='title_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productcharacteristicsblock',
            name='title_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='button_text_de',
            field=models.CharField(default='Request', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='button_text_sk',
            field=models.CharField(default='Request', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='name_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='name_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='tag_de',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='tag_sk',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='productmodulecharacteristic',
            name='name_de',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productmodulecharacteristic',
            name='name_sk',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productmodulesblock',
            name='subtitle_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productmodulesblock',
            name='subtitle_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productmodulesblock',
            name='title_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productmodulesblock',
            name='title_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productpresentationinfo',
            name='description_de',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='productpresentationinfo',
            name='description_sk',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='productpresentationinfo',
            name='title_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productpresentationinfo',
            name='title_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='producttextblock',
            name='text_de',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='producttextblock',
            name='text_sk',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='producttextblock',
            name='title_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='producttextblock',
            name='title_sk',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
