# Generated by Codex on 2026-01-05

import django.db.models.deletion
from django.db import migrations, models


def copy_productimage_alt_translations(apps, schema_editor):
    ProductImage = apps.get_model("portal", "ProductImage")
    ProductImageTranslation = apps.get_model(
        "portal", "ProductImageTranslation"
    )
    db_alias = schema_editor.connection.alias
    translations = []
    for image in ProductImage.objects.using(db_alias).all():
        for lang in ("en", "de", "sk"):
            field_name = f"alt_{lang}"
            value = getattr(image, field_name, None)
            if (value is None or (isinstance(value, str) and value.strip() == "")) and lang == "en":
                value = image.alt
            if value is None:
                continue
            if isinstance(value, str):
                value = value.strip()
            if value == "":
                continue
            translations.append(
                ProductImageTranslation(
                    image_id=image.id,
                    lang=lang,
                    alt=value,
                )
            )
    ProductImageTranslation.objects.using(db_alias).bulk_create(
        translations, ignore_conflicts=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0015_portalproduct_description_en_portalproduct_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("sk", "Slovak"),
                        ],
                        max_length=2,
                    ),
                ),
                ("alt", models.CharField(max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="portal.productimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image translation",
                "verbose_name_plural": "Product image translations",
                "unique_together": {("image", "lang")},
            },
        ),
        migrations.RunPython(
            copy_productimage_alt_translations,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_de",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_en",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_sk",
        ),
    ]
