# Generated by Codex on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_productimage_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcharacteristic",
            name="description",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="productcharacteristic",
            name="description_de",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productcharacteristic",
            name="description_en",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productcharacteristic",
            name="description_sk",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productmodule",
            name="description",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="productmodule",
            name="description_de",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="productmodule",
            name="description_en",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="productmodule",
            name="description_sk",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="productmodulecharacteristic",
            name="description",
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="productmodulecharacteristic",
            name="description_de",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="productmodulecharacteristic",
            name="description_en",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="productmodulecharacteristic",
            name="description_sk",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="productpresentationinfo",
            name="description",
            field=models.TextField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="productpresentationinfo",
            name="description_de",
            field=models.TextField(max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name="productpresentationinfo",
            name="description_en",
            field=models.TextField(max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name="productpresentationinfo",
            name="description_sk",
            field=models.TextField(max_length=8192, null=True),
        ),
    ]
