# Generated by Django 5.2.7 on 2026-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_increase_description_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalproduct',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalproduct',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalproduct',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalproduct',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portalproduct',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portalproduct',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='name_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='name_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='name_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristicsblock',
            name='title_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristicsblock',
            name='title_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcharacteristicsblock',
            name='title_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='button_text_es',
            field=models.CharField(default='Request', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='button_text_fr',
            field=models.CharField(default='Request', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='button_text_it',
            field=models.CharField(default='Request', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='description_es',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='description_fr',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='description_it',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='name_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='name_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='name_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='tag_es',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='tag_fr',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='tag_it',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='description_es',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='description_fr',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='description_it',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='name_es',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='name_fr',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productmodulecharacteristic',
            name='name_it',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productmoduleimage',
            name='alt_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmoduleimage',
            name='alt_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmoduleimage',
            name='alt_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='subtitle_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='subtitle_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='subtitle_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='title_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='title_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodulesblock',
            name='title_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='description_es',
            field=models.TextField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='description_fr',
            field=models.TextField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='description_it',
            field=models.TextField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='title_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='title_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productpresentationinfo',
            name='title_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='text_es',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='text_fr',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='text_it',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='title_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='title_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='producttextblock',
            name='title_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productimagetranslation',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('sk', 'Slovak'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], max_length=2),
        ),
    ]
