services:
  db:
    image: postgres:16-alpine
    container_name: aidef-db
    environment:
      POSTGRES_DB: aidef
      POSTGRES_USER: aidef
      POSTGRES_PASSWORD: aidef_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aidef-backend
    environment:
      POSTGRES_DB: aidef
      POSTGRES_USER: aidef
      POSTGRES_PASSWORD: aidef_password
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"

      DJANGO_SECRET: "django-insecure-=#z3fc*6goc8=yu0(#r*q%vovcg@v3-u2+wvbyyz4s$64o!tvz"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "173.242.51.20,localhost,127.0.0.1"
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - ./backend/media:/app/media
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aidef-web
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/static
    
volumes:
  postgres_data:
  static_volume:
