# Generated by Django 5.2.7 on 2025-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
