# Generated by Django 5.2.7 on 2025-12-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productfeature_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeature',
            options={'ordering': ('order',), 'verbose_name': 'Product feature', 'verbose_name_plural': 'Product features'},
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='description',
            field=models.TextField(max_length=256),
        ),
    ]
