# Generated by Django 5.2.7 on 2025-12-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_productfeature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_features', to='main.product')),
            ],
            options={
                'verbose_name': 'Product sub feature',
                'verbose_name_plural': 'Product sub features',
                'ordering': ('order',),
            },
        ),
    ]
