# Generated by Django 5.2.7 on 2025-12-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productsubfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('variant', models.CharField(choices=[('hero', 'Hero'), ('split', 'Split'), ('bullets', 'Bullets'), ('cta', 'Call to action')], default='hero', max_length=20)),
                ('background_image', models.ImageField(blank=True, upload_to='products/detail_blocks/backgrounds/%Y/%m/')),
                ('illustration', models.ImageField(blank=True, upload_to='products/detail_blocks/illustrations/%Y/%m/')),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_blocks', to='main.product')),
            ],
            options={
                'verbose_name': 'Product detail block',
                'verbose_name_plural': 'Product detail blocks',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductDetailPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='main.productdetailblock')),
            ],
            options={
                'verbose_name': 'Product detail point',
                'verbose_name_plural': 'Product detail points',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductTechFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='Small label shown above the headline.', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_focus', to='main.product')),
            ],
            options={
                'verbose_name': 'Product tech focus',
                'verbose_name_plural': 'Product tech focus',
            },
        ),
        migrations.CreateModel(
            name='ProductTechFocusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Frontend icon identifier, e.g. lucide name.', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of badges for this focus item.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_focus_items', to='main.product')),
            ],
            options={
                'verbose_name': 'Product tech focus item',
                'verbose_name_plural': 'Product tech focus items',
                'ordering': ('order', 'id'),
            },
        ),
    ]
