# Generated by Django 5.2.7 on 2025-12-07 11:58

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productdetailblock_productdetailpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailpoint',
            name='block',
        ),
        migrations.RemoveField(
            model_name='producttechfocus',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttechfocusitem',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (e.g. lucide icon name).', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of up to 3 badges for this tech item.', validators=[main.models.validate_tags_max_three])),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='main.product')),
            ],
            options={
                'verbose_name': 'Product technology',
                'verbose_name_plural': 'Product technology',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='ProductDetailBlock',
        ),
        migrations.DeleteModel(
            name='ProductDetailPoint',
        ),
        migrations.DeleteModel(
            name='ProductTechFocus',
        ),
        migrations.DeleteModel(
            name='ProductTechFocusItem',
        ),
    ]
