# Generated by Django 5.2.7 on 2025-12-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_productdetailpoint_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttech',
            name='icon',
        ),
    ]
