# Generated by Django 5.2.7 on 2025-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_producttech_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttech',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon identifier (e.g. lucide icon name).', max_length=64),
        ),
    ]
