# Generated by Django 5.2.7 on 2025-12-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_producttech_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttech',
            name='icon',
        ),
    ]
