# Generated by Django 5.2.7 on 2025-12-07 13:27

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_producttech_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHeroFeatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('background_image', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_feature_blocks', to='main.product')),
            ],
            options={
                'verbose_name': 'Product hero feature block',
                'verbose_name_plural': 'Product hero feature blocks',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of up to 3 badges for this tech item.', validators=[main.models.validate_tags_max_three])),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='main.product')),
            ],
            options={
                'verbose_name': 'Product technology',
                'verbose_name_plural': 'Product technology',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='ProductTech',
        ),
    ]
