# Generated by Django 5.2.7 on 2025-12-07 13:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productherofeatureblock_producttechnology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttechnology',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of up to 3 badges for this technology.', validators=[main.models.validate_tags_max_three]),
        ),
    ]
