# Generated by Django 5.2.7 on 2025-12-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_producttechnology_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttechnology',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='main.product'),
        ),
    ]
