# Generated by Django 5.2.7 on 2025-12-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_producttechnology_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('background_image', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('with_logo', models.BooleanField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_blocks', to='main.product')),
            ],
            options={
                'verbose_name': 'Product feature block',
                'verbose_name_plural': 'Product feature blocks',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='ProductHeroFeatureBlock',
        ),
    ]
