# Generated by Django 5.2.7 on 2025-12-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_productfeatureblock_delete_productherofeatureblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=128)),
                ('description_1', models.TextField(max_length=256)),
                ('image_1', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('title_2', models.CharField(max_length=128)),
                ('description_2', models.TextField(max_length=256)),
                ('image_2', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='main.product')),
            ],
            options={
                'verbose_name': 'Product info block',
                'verbose_name_plural': 'Product info blocks',
                'ordering': ('order',),
            },
        ),
    ]
