# Generated by Django 5.2.7 on 2025-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_productinfoblock'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE main_productinfoblock "
                        "ALTER COLUMN description_1 TYPE jsonb "
                        "USING to_jsonb(description_1);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE main_productinfoblock "
                        "ALTER COLUMN description_1 TYPE text "
                        "USING description_1::text;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE main_productinfoblock "
                        "ALTER COLUMN description_2 TYPE jsonb "
                        "USING to_jsonb(description_2);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE main_productinfoblock "
                        "ALTER COLUMN description_2 TYPE text "
                        "USING description_2::text;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='productinfoblock',
                    name='description_1',
                    field=models.JSONField(max_length=512),
                ),
                migrations.AlterField(
                    model_name='productinfoblock',
                    name='description_2',
                    field=models.JSONField(max_length=512),
                ),
            ],
        ),
    ]
