# Generated by Django 5.2.7 on 2025-12-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_productinfoblock_description_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCTABlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=128)),
                ('background_image', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('has_button', models.BooleanField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta_blocks', to='main.product')),
            ],
            options={
                'verbose_name': 'Product CTA block',
                'verbose_name_plural': 'Product CTA blocks',
                'ordering': ('order',),
            },
        ),
    ]
