# Generated by Django 5.2.7 on 2025-12-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='productfeatureblock',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='productinfoblock',
            name='description_1',
            field=models.JSONField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='productinfoblock',
            name='description_2',
            field=models.JSONField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='productsubfeature',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='producttechnology',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
