# Generated by Codex on 2025-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_product_options_remove_product_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_de",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_sk",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_sk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_sk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productctablock",
            name="name_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productctablock",
            name="name_sk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productctablock",
            name="title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productctablock",
            name="title_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="description_de",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="description_sk",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="name_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="name_sk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="value_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="value_sk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productfeatureblock",
            name="description_de",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productfeatureblock",
            name="description_sk",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productfeatureblock",
            name="name_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productfeatureblock",
            name="name_sk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productfeatureblock",
            name="title_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productfeatureblock",
            name="title_sk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="alt_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="alt_sk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_sk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productinfoblock",
            name="title_1_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productinfoblock",
            name="title_1_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productinfoblock",
            name="title_2_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productinfoblock",
            name="title_2_sk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="productsubfeature",
            name="description_de",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productsubfeature",
            name="description_sk",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productsubfeature",
            name="name_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productsubfeature",
            name="name_sk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producttechnology",
            name="description_de",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="producttechnology",
            name="description_sk",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="producttechnology",
            name="name_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producttechnology",
            name="name_sk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
