# Generated by Django 4.2.27 on 2026-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_modeltranslation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='description_en',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='description_en',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_1_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_2_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='description_en',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='description_en',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_sk',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productctablock',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productctablock',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productctablock',
            name='title_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productctablock',
            name='title_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfeatureblock',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfeatureblock',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfeatureblock',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfeatureblock',
            name='title_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productinfoblock',
            name='title_1_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productinfoblock',
            name='title_1_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productinfoblock',
            name='title_2_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productinfoblock',
            name='title_2_sk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productsubfeature',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsubfeature',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttechnology',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttechnology',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
