# Generated by Codex on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_productimage_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfeature",
            name="description",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="description_de",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="description_en",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="description_sk",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productfeatureblock",
            name="description",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="productfeatureblock",
            name="description_de",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productfeatureblock",
            name="description_en",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productfeatureblock",
            name="description_sk",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productinfoblock",
            name="description_1",
            field=models.JSONField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="productinfoblock",
            name="description_2",
            field=models.JSONField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="productsubfeature",
            name="description",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="productsubfeature",
            name="description_de",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productsubfeature",
            name="description_en",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="productsubfeature",
            name="description_sk",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="producttechnology",
            name="description",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="producttechnology",
            name="description_de",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="producttechnology",
            name="description_en",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="producttechnology",
            name="description_sk",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
