# Generated by Codex on 2026-02-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_increase_description_lengths"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("support", "Support"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("product", models.CharField(blank=True, max_length=120)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("country_name", models.CharField(blank=True, max_length=120)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("address_line3", models.CharField(blank=True, max_length=255)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("source", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contact request",
                "verbose_name_plural": "Contact requests",
                "ordering": ("-created_at",),
            },
        ),
    ]
