# Generated by Django 5.2.7 on 2026-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_seed_civil_product_swift'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='civilcategory',
            name='name_es',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='civilcategory',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='civilcategory',
            name='name_it',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='civilproduct',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilproduct',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilproduct',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilproduct',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilproduct',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilproduct',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilproductctablock',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductctablock',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductctablock',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductctablock',
            name='title_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductctablock',
            name='title_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductctablock',
            name='title_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='value_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='value_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='value_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductfeatureblock',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductgallery',
            name='alt_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilproductgallery',
            name='alt_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilproductgallery',
            name='alt_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilproductinfoblock',
            name='title_1_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductinfoblock',
            name='title_1_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductinfoblock',
            name='title_1_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductinfoblock',
            name='title_2_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductinfoblock',
            name='title_2_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductinfoblock',
            name='title_2_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproducttechnology',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproducttechnology',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproducttechnology',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='civilproducttechnology',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproducttechnology',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilproducttechnology',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='title_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='title_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productctablock',
            name='title_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureblock',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='alt_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_1_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_1_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_1_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_2_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_2_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinfoblock',
            name='title_2_it',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='description_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='description_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='description_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttechnology',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilproductimagetranslation',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('sk', 'Slovak'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productimagetranslation',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('sk', 'Slovak'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], max_length=2),
        ),
    ]
