# Generated by Django 5.2.7 on 2026-02-09 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_category_name_es_category_name_fr_category_name_it_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDroneSliderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/drone_slider/%Y/%m/')),
                ('video', models.FileField(blank=True, help_text='Optional preview video played on card hover.', upload_to='products/drone_slider/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drone_slider_media', to='main.product')),
            ],
            options={
                'verbose_name': 'Product DroneSlider media',
                'verbose_name_plural': 'Product DroneSlider media',
            },
        ),
    ]
