# Generated by Django 5.2.7 on 2026-02-10 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_productdroneslidermedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('spam', 'Spam')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
