# Generated by Django 5.2.7 on 2026-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_contactrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.URLField(help_text='LinkedIn embed URL, for example: https://www.linkedin.com/embed/feed/update/urn:li:share:...', max_length=600)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LinkedIn post',
                'verbose_name_plural': 'LinkedIn posts',
                'ordering': ('order', '-created_at', 'pk'),
            },
        ),
    ]
