# Generated by Django 5.2.7 on 2026-02-23 14:02

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_linkedinpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog author',
                'verbose_name_plural': 'Blog authors',
                'ordering': ('order', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateField(blank=True, db_index=True, null=True)),
                ('read_minutes', models.PositiveSmallIntegerField(default=3)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='main.blogauthor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='main.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'ordering': ('order', '-published_at', '-created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='BlogPostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('anchor_id', models.SlugField(blank=True, max_length=120)),
                ('paragraphs', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('bullets', models.JSONField(blank=True, help_text='JSON array of bullet strings.', null=True, validators=[main.models.validate_string_list])),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.blogpost')),
            ],
            options={
                'verbose_name': 'Blog post section',
                'verbose_name_plural': 'Blog post sections',
                'ordering': ('order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('post', 'anchor_id'), name='main_blogpostsection_unique_anchor_per_post')],
            },
        ),
    ]
