# Generated by Django 5.2.7 on 2026-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_blogauthor_blogcategory_blogpost_blogpostsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/'),
        ),
    ]
