# Generated by Django 5.2.7 on 2026-03-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_blogpost_hero_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LinkedInPost",
        ),
    ]
