# Generated by Django 5.2.7 on 2026-03-05 13:00

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_delete_linkedinpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='name_de',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='name_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='name_es',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='name_fr',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='name_it',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='name_sk',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='role_de',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='role_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='role_es',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='role_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='role_it',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='role_sk',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_de',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_es',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_it',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_sk',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='bullets_de',
            field=models.JSONField(blank=True, help_text='JSON array of bullet strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='bullets_en',
            field=models.JSONField(blank=True, help_text='JSON array of bullet strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='bullets_es',
            field=models.JSONField(blank=True, help_text='JSON array of bullet strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='bullets_fr',
            field=models.JSONField(blank=True, help_text='JSON array of bullet strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='bullets_it',
            field=models.JSONField(blank=True, help_text='JSON array of bullet strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='bullets_sk',
            field=models.JSONField(blank=True, help_text='JSON array of bullet strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='paragraphs_de',
            field=models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='paragraphs_en',
            field=models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='paragraphs_es',
            field=models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='paragraphs_fr',
            field=models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='paragraphs_it',
            field=models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='paragraphs_sk',
            field=models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list]),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='title_sk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
