# Generated by Django 5.2.7 on 2026-03-09 20:15

import django.db.models.deletion
import main.models
from django.db import migrations, models


TRANSLATED_LANGUAGES = ("en", "de", "sk", "es", "fr", "it")


def copy_sections_to_blocks(apps, schema_editor):
    BlogPostBlock = apps.get_model("main", "BlogPostBlock")
    BlogPostSection = apps.get_model("main", "BlogPostSection")

    blocks_to_create = []
    for section in BlogPostSection.objects.all().iterator():
        payload = {
            "post_id": section.post_id,
            "kind": "bullets" if section.bullets else "text",
            "title": section.title,
            "anchor_id": section.anchor_id,
            "paragraphs": section.paragraphs,
            "items": section.bullets,
            "order": section.order,
        }
        for language_code in TRANSLATED_LANGUAGES:
            payload[f"title_{language_code}"] = getattr(
                section,
                f"title_{language_code}",
                None,
            )
            payload[f"paragraphs_{language_code}"] = getattr(
                section,
                f"paragraphs_{language_code}",
                None,
            )
            payload[f"items_{language_code}"] = getattr(
                section,
                f"bullets_{language_code}",
                None,
            )
        blocks_to_create.append(BlogPostBlock(**payload))

    if blocks_to_create:
        BlogPostBlock.objects.bulk_create(blocks_to_create)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_product_dropdown_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('bullets', 'Bullets'), ('quote', 'Quote'), ('image', 'Image'), ('divider', 'Divider')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_de', models.CharField(blank=True, max_length=255, null=True)),
                ('title_sk', models.CharField(blank=True, max_length=255, null=True)),
                ('title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('title_it', models.CharField(blank=True, max_length=255, null=True)),
                ('anchor_id', models.SlugField(blank=True, max_length=120)),
                ('paragraphs', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('paragraphs_en', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('paragraphs_de', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('paragraphs_sk', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('paragraphs_es', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('paragraphs_fr', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('paragraphs_it', models.JSONField(blank=True, help_text='JSON array of paragraph strings.', null=True, validators=[main.models.validate_string_list])),
                ('items', models.JSONField(blank=True, help_text='JSON array of list item strings.', null=True, validators=[main.models.validate_string_list])),
                ('items_en', models.JSONField(blank=True, help_text='JSON array of list item strings.', null=True, validators=[main.models.validate_string_list])),
                ('items_de', models.JSONField(blank=True, help_text='JSON array of list item strings.', null=True, validators=[main.models.validate_string_list])),
                ('items_sk', models.JSONField(blank=True, help_text='JSON array of list item strings.', null=True, validators=[main.models.validate_string_list])),
                ('items_es', models.JSONField(blank=True, help_text='JSON array of list item strings.', null=True, validators=[main.models.validate_string_list])),
                ('items_fr', models.JSONField(blank=True, help_text='JSON array of list item strings.', null=True, validators=[main.models.validate_string_list])),
                ('items_it', models.JSONField(blank=True, help_text='JSON array of list item strings.', null=True, validators=[main.models.validate_string_list])),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_alt_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image_alt_de', models.CharField(blank=True, max_length=255, null=True)),
                ('image_alt_sk', models.CharField(blank=True, max_length=255, null=True)),
                ('image_alt_es', models.CharField(blank=True, max_length=255, null=True)),
                ('image_alt_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('image_alt_it', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.blogpost')),
            ],
            options={
                'verbose_name': 'Blog post block',
                'verbose_name_plural': 'Blog post blocks',
                'ordering': ('order', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('anchor_id', ''), _negated=True), fields=('post', 'anchor_id'), name='main_blogpostblock_unique_anchor_per_post')],
            },
        ),
        migrations.RunPython(copy_sections_to_blocks, noop_reverse),
    ]
