# Generated by Django 5.2.7 on 2026-03-09 21:12

import html
from django.db import migrations, models


TRANSLATED_LANGUAGES = ("en", "de", "sk", "es", "fr", "it")


def paragraphs_to_html(value):
    if not value:
        return ""
    cleaned = [str(item).strip() for item in value if str(item).strip()]
    if not cleaned:
        return ""
    return "".join(f"<p>{html.escape(item)}</p>" for item in cleaned)


def copy_paragraphs_to_html(apps, schema_editor):
    BlogPostBlock = apps.get_model("main", "BlogPostBlock")

    for block in BlogPostBlock.objects.all().iterator():
        update_fields = []

        if not (block.html or "").strip():
            block.html = paragraphs_to_html(block.paragraphs)
            if block.html:
                update_fields.append("html")

        for language_code in TRANSLATED_LANGUAGES:
            html_field = f"html_{language_code}"
            paragraphs_field = f"paragraphs_{language_code}"
            html_value = getattr(block, html_field, "") or ""
            if html_value.strip():
                continue
            next_value = paragraphs_to_html(getattr(block, paragraphs_field, None))
            if not next_value:
                continue
            setattr(block, html_field, next_value)
            update_fields.append(html_field)

        if update_fields:
            block.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_blogpostblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostblock',
            name='html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostblock',
            name='html_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostblock',
            name='html_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostblock',
            name='html_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostblock',
            name='html_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostblock',
            name='html_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostblock',
            name='html_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(copy_paragraphs_to_html, noop_reverse),
    ]
