# Generated by Django 5.2.7 on 2026-03-10 00:00

import html

from django.db import migrations


TRANSLATED_LANGUAGES = ("en", "de", "sk", "es", "fr", "it")
BULLETS_KIND = "bullets"


def paragraphs_to_html(value):
    if not value:
        return ""
    cleaned = [str(item).strip() for item in value if str(item).strip()]
    if not cleaned:
        return ""
    return "".join(f"<p>{html.escape(item)}</p>" for item in cleaned)


def items_to_html(value):
    if not value:
        return ""
    cleaned = [str(item).strip() for item in value if str(item).strip()]
    if not cleaned:
        return ""
    items_markup = "".join(f"<li>{html.escape(item)}</li>" for item in cleaned)
    return f"<ul>{items_markup}</ul>"


def block_lists_to_html(kind, paragraphs, items):
    if kind == BULLETS_KIND:
        return items_to_html(items) or paragraphs_to_html(paragraphs)
    return paragraphs_to_html(paragraphs)


def promote_lists_to_html(apps, schema_editor):
    BlogPostBlock = apps.get_model("main", "BlogPostBlock")

    for block in BlogPostBlock.objects.all().iterator():
        update_fields = []

        if not (block.html or "").strip():
            next_value = block_lists_to_html(block.kind, block.paragraphs, block.items)
            if next_value:
                block.html = next_value
                update_fields.append("html")

        for language_code in TRANSLATED_LANGUAGES:
            html_field = f"html_{language_code}"
            html_value = getattr(block, html_field, "") or ""
            if html_value.strip():
                continue

            next_value = block_lists_to_html(
                block.kind,
                getattr(block, f"paragraphs_{language_code}", None),
                getattr(block, f"items_{language_code}", None),
            )
            if not next_value:
                continue

            setattr(block, html_field, next_value)
            update_fields.append(html_field)

        if update_fields:
            block.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_blogpostblock_html_blogpostblock_html_de_and_more"),
    ]

    operations = [
        migrations.RunPython(promote_lists_to_html, noop_reverse),
    ]
