# Generated by Django 5.2.7 on 2026-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_blogpostblock_promote_lists_to_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='address_line3',
        ),
    ]
