# Generated by Django 5.2.7 on 2026-03-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_contactrequest_address_line3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFinalCTABlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_sk', models.CharField(blank=True, max_length=100, null=True)),
                ('name_es', models.CharField(blank=True, max_length=100, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('name_it', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_de', models.CharField(max_length=128, null=True)),
                ('title_sk', models.CharField(max_length=128, null=True)),
                ('title_es', models.CharField(max_length=128, null=True)),
                ('title_fr', models.CharField(max_length=128, null=True)),
                ('title_it', models.CharField(max_length=128, null=True)),
                ('background_image', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('has_button', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_cta_block', to='main.product')),
            ],
            options={
                'verbose_name': 'Product final CTA block',
                'verbose_name_plural': 'Product final CTA blocks',
            },
        ),
    ]
