# Generated by Django 5.2.7 on 2026-04-21 11:35

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_blogpostheroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilproductfeature',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Optional uploaded icon file. If set, it takes precedence.', null=True, upload_to='overview_icons/%Y/%m/', validators=[main.models.validate_svg_file]),
        ),
        migrations.AddField(
            model_name='civilproductfeature',
            name='icon_lucide',
            field=models.CharField(blank=True, help_text='Optional Lucide icon name, e.g. ShieldCheck.', max_length=64),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Optional uploaded icon file. If set, it takes precedence.', null=True, upload_to='overview_icons/%Y/%m/', validators=[main.models.validate_svg_file]),
        ),
        migrations.AddField(
            model_name='civilproductsubfeature',
            name='icon_lucide',
            field=models.CharField(blank=True, help_text='Optional Lucide icon name, e.g. ShieldCheck.', max_length=64),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Optional uploaded icon file. If set, it takes precedence.', null=True, upload_to='overview_icons/%Y/%m/', validators=[main.models.validate_svg_file]),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='icon_lucide',
            field=models.CharField(blank=True, help_text='Optional Lucide icon name, e.g. ShieldCheck.', max_length=64),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Optional uploaded icon file. If set, it takes precedence.', null=True, upload_to='overview_icons/%Y/%m/', validators=[main.models.validate_svg_file]),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='icon_lucide',
            field=models.CharField(blank=True, help_text='Optional Lucide icon name, e.g. ShieldCheck.', max_length=64),
        ),
    ]
